### ISSUE TITLE
FLTK does not build on my Endeavour OS system, because HAVE_TRUNC is not defined when the trunc function *does* exist. 

### ISSUE THREAD

**Issue by Explodey-Wolf** [fltk/fltk#1049]
**Describe the bug**
fltk-sys will fail to build in CMAKE. It will fail with the following error:
```
/home/wolf/fltk/src/Fl_Timeout.cxx:27:22: error: ‘double trunc(double)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
   27 | static inline double trunc(double x) { return x >= 0 ? floor(x) : ceil(x); }
      |                      ^~~~~
In file included from /usr/include/features.h:511,
                 from /usr/include/time.h:25,
                 from /home/wolf/fltk/src/../FL/platform_types.h:84,
                 from /home/wolf/fltk/src/../FL/Fl.H:26,
                 from /home/wolf/fltk/src/Fl_Timeout.h:21,
                 from /home/wolf/fltk/src/Fl_Timeout.cxx:20:
/usr/include/bits/mathcalls.h:320:1: note: previous declaration of ‘double trunc(double)’
  320 | __MATHCALLX (trunc,, (_Mdouble_ __x), (__const__));
      | ^~~~~~~~~~~
make[2]: *** [src/CMakeFiles/fltk.dir/build.make:1220: src/CMakeFiles/fltk.dir/Fl_Timeout.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:390: src/CMakeFiles/fltk.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**To Reproduce**
I'm not sure if this is reproducible as I don't have access to other systems. However, the steps I took was:
1. `git clone https://github.com/fltk/fltk.git`
2. `cd fltk`
3. `mkdir build`
4. `cd build`
5. `cmake ..`
6. `make`

**Expected behavior**
It compiles.

**Screenshots**
None.

**FLTK Version**
Newest commit at the time was 9e35b0216f384f815284d6e8ee4ee9fcce3af01a
I believe it's 1.3.9

**FLTK Configure / Build Options**
In the previous thing.

**Operating System / Platform:**
Linux EndeavourOS
**Linux/Unix Runtime, if applicable:**
X11

**Additional context**
None.

**Comment by ManoloFLTK** [comment]
Please, report here what version of cmake are you using. Currently, FLTK uses cmake's `check_function_exists()` which came with cmake version 3.8 to correctly setup the value of HAVE_TRUNC. Earlier cmake versions use `CHECK_FUNCTION_EXISTS()`.

Please, notice that FLTK now requires version 3.15 or above of cmake, as stated in REAMAE_CMake.txt.

Notice also that after `git clone`you get the main branch which is FLTK 1.4.0 (still in beta state). To get 1.3.x you have to do `git checkout branch-1.3`.

**Comment by Albrecht-S** [comment]
@Explodey-Wolf Yes, please report your CMake version. Mine (on EndeavourOS) is a very recent one:
`cmake version 3.30.2`

I installed a current version of EndeavourOS (`EndeavourOS_Endeavour-2024.06.25.iso`) in a VM, updated the system, and built FLTK w/o issues.
IIRC the only two packages I had to install to build FLTK (X11) were:
```
pacman -S ninja           # ninja build system
pacman -S cmake           # cmake
```
Everything else worked OOTB.

I wonder if you have an older version of EndeavourOS installed, can you give us some details? When did you update (upgrade) your OS the last time? You may try `sudo pacman -Syu` to upgrade your system to the latest version (but decide yourself whether this is appropriate for you).

@ManoloFLTK Capital letters in function/macro calls don't matter, and a user can't use CMake versions lower than 3.15 w/o editing the FLTK CMake files (which would definitely cause bugs, and which the user (@Explodey-Wolf ) should have told us.

**Comment by Explodey-Wolf** [comment]
Thank your for your responses. I am using cmake version 3.30.2. Switching to version 1.3 resolves the error, so apparently fltk-rs uses 1.4, which is where I originally got this error. My last update was at most a month ago, but probably sooner. Oddly enough, 1.3 has a *different* error with strdup not being defined...

**Comment by MoAlyousef** [comment]
Just to confirm that fltk-rs uses FLTK 1.4. Regarding CMake’s check_function_exists(), it seems it has some limitations:

https://cmake.org/cmake/help/latest/module/CheckFunctionExists.html

Would it be possible to use check_symbol_exists as the cmake docs recommend? Would it help with libm math functions?

**Comment by ManoloFLTK** [comment]
OK. So @Albrecht-S reports that FLTK builds OOTB under EndeavourOS whereas @Explodey-Wolf reports an error and that his/her system is the same or very to close to Albrecht's. I'm tempted to hypothesize that there's a mixture of installed 1.3 and git 1.4 code in @Explodey-Wolf's system. Please, triple check that.

Otherwise, here is how to follow @MoAlyousef's suggestion:

Please, try replacing line # 238 of file `CMake/resources.cmake` that's presently
`check_function_exists(trunc                     HAVE_TRUNC)`
by
```
#check_function_exists(trunc                     HAVE_TRUNC)
include(CheckCXXSymbolExists)
check_cxx_symbol_exists(trunc "math.h" HAVE_TRUNC)
```
and report if you get HAVE_TRUNC defined to 1 in your file `build/config.h`.

**Comment by ManoloFLTK** [comment]
@Explodey-Wolf reports this error
```
/usr/include/bits/mathcalls.h:320:1: note: previous declaration of ‘double trunc(double)’
  320 | __MATHCALLX (trunc,, (_Mdouble_ __x), (__const__));
```
which indicates `trunc()` is defined as a macro by EndeavourOS. Consequently
`check_function_exists(trunc  HAVE_TRUNC)`is expected to fail as documented by CMake:
> check_function_exists() can’t detect functions that are inlined in headers or specified as a macro.

Using `check_cxx_symbol_exists()` is probably the way to go.

**Comment by Albrecht-S** [comment]
@MoAlyousef Thanks for your hint, this is very much appreciated. Indeed I tried this already and it worked, but since I couldn't reproduce the error on my EndeavourOS system I wasn't sure what to suggest and wanted to test further.

@ManoloFLTK It's probably not necessary to use `check_cxx_symbol_exists()`, I'd prefer `check_symbol_exists()` because all these function checks (there are 13 of them in our current code) should also work under plain C,  i.e. the respective functions should be available in C.

@Explodey-Wolf Please test Manolo's suggestion and report here what you find **_with FLTK 1.4_**. Note that you **must** use a **_fresh (clean) build folder_** for testing because these test result variables are cached by CMake. That's my suggestion. OTOH, if you want to preserve your existing build folder, you can add
```
unset(HAVE_TRUNC CACHE)
```
right before the `check_cxx_symbol_exists()` as Manolo suggests.

It would be even more helpful if you could change Manolo's suggestion to:
```
#check_function_exists(trunc                     HAVE_TRUNC)
unset(HAVE_TRUNC CACHE) # clear cache (TEST ONLY)
include(CheckSymbolExists)
check_symbol_exists(trunc "math.h" HAVE_TRUNC)
```
so we can see that the (supposedly simpler) macro `check_symbol_exists()` works as well.

Thanks in advance.

**Comment by Explodey-Wolf** [comment]
> I'm tempted to hypothesize that there's a mixture of installed 1.3 and git 1.4 code in @Explodey-Wolf's system. Please, triple check that.
I have checked, and I don't have any of fltk installed globally on my system.
> which indicates trunc() is defined as a macro by EndeavourOS
I believe trunc() is actually defined as a function _by_ a macro. This is also true in a new sandbox I opened up to test, which runs on Debian.

I did try @MoAlyousef 's suggestion, but it failed with the same error, and it was defined as 0.
What @Albrecht-S provided actually _did_ work! However, it failed at step `Linking CXX executable ../bin/fluid` undefined reference errors seemingly on every line...

**Comment by Explodey-Wolf** [comment]
Should I make another issue for the undefined reference errors? They look like this if it matters.
```
/usr/bin/ld: ../lib/libfltk.a(flstring.c.o): in function `fl_strlcat':
/home/wolf/fltk/src/flstring.c:36:(.text+0x39): undefined reference to `__ubsan_handle_nonnull_arg'
/usr/bin/ld: /home/wolf/fltk/src/flstring.c:45:(.text+0x8f): undefined reference to `__ubsan_handle_nonnull_arg'
/usr/bin/ld: /home/wolf/fltk/src/flstring.c:53:(.text+0x11c): undefined reference to `__ubsan_handle_pointer_overflow'
/usr/bin/ld: /home/wolf/fltk/src/flstring.c:53:(.text+0x146): undefined reference to `__ubsan_handle_nonnull_arg'
/usr/bin/ld: /home/wolf/fltk/src/flstring.c:53:(.text+0x160): undefined reference to `__ubsan_handle_nonnull_arg'
/usr/bin/ld: /home/wolf/fltk/src/flstring.c:54:(.text+0x1df): undefined reference to `__ubsan_handle_pointer_overflow'
/usr/bin/ld: /home/wolf/fltk/src/flstring.c:54:(.text+0x1fd): undefined reference to `__ubsan_handle_type_mismatch_v1'
/usr/bin/ld: ../lib/libfltk.a(flstring.c.o): in function `fl_ascii_strcasecmp':
...
```

**Comment by Albrecht-S** [comment]
> What @Albrecht-S provided actually did work!

@Explodey-Wolf OK, that's a step forward, but I have two questions to be absolutely sure:
1. Did you try Manolo's suggestion **_in a fresh/clear build folder_**, and did this attempt use `check_cxx_symbol_exists()`, i.e. with `_cxx_` ? See also my note about cached result variables.
2. Did you use my full proposal with `unset(HAVE_TRUNC CACHE)` and `check_symbol_exists()`, i.e. w/o `_cxx_` ?

Regarding undefined symbols `__ubsan_*` see follow-up comment.

**Comment by Albrecht-S** [comment]
> undefined reference to `__ubsan_handle_nonnull_arg' ...

@Explodey-Wolf A quick search found a question and [answer on stackoverflow](https://stackoverflow.com/questions/52333340/undefined-reference-to-ubsan-handle-nonnull-arg). The gist of the answer is
> In order to check your program with ubsan, compile **and link** the program with **-fsanitize=undefined** option.

OK, that looks easy enough, but I don't know why this issue exists in your build in the first place. One more question:
Do you build for 'Debug' or 'Release'? Your cmake command above doesn't specify this, i.e. it's kinda "undefined" WRT CMake. To rule out issues caused by this, please specify either `-D CMAKE_BUILD_TYPE=Debug` or `-D CMAKE_BUILD_TYPE=Release` on the commandline or edit the cache variable `CMAKE_BUILD_TYPE`. Please make sure that the case of the string(s) is correct as given above since this is option case-sensitive.

Once you did this (both options), please report if any or both fix the issue.

The next step would be to define the required linker option within `CMake`, either on the commandline:
```
-D CMAKE_EXE_LINKER_FLAGS='-fsanitize=undefined'
```
or edit the cache in `ccmake` or `cmake-gui`. Note that this is an 'advanced' setting, you need to tick the 'Advanced' check button.

Please report again, if this worked.

If neither of this works, please open a new [`GitHub Discussion` thread in the `Q&A` section](https://github.com/fltk/fltk/discussions/categories/q-a).

**Comment by Albrecht-S** [comment]
FTR: I assigned this issue to me and will do the following:
- [ ] Replace `check_function_exists(trunc HAVE_TRUNC)` with `check_symbol_exists(..)`
- [ ] Investigate whether and how to replace the other 12 occurrences of `check_function_exists()`

Note that the replacement requires one or more specific header files to be included and maybe a library to be linked explicitly. That's why I wrote "investigate".

I may close this issue when the first item is done and maybe I'll open another issue for the second item - or not.

**Comment by Explodey-Wolf** [comment]
>Did you try Manolo's suggestion in a fresh/clear build folder, and did this attempt use check_cxx_symbol_exists(), i.e. with _cxx_ ? See also my note about cached result variables.
  Did you use my full proposal with unset(HAVE_TRUNC CACHE) and check_symbol_exists(), i.e. w/o _cxx_ ?

I completely deleted the build folder, and used the _cxx_ one. 

> Do you build for 'Debug' or 'Release'?

I've never used CMAKE before, so I'm not sure what my default is, but it appears it's Debug. When I compiled with Release, it had an extra warning before the error, but errored at the same spot. 

The `-fsanitize` flag works! I find it very odd that this only has occurred for me.
I'll try running this in a vm and see if it has the same problem.

**Comment by Explodey-Wolf** [comment]
Hi @Albrecht-S ! I have more information. I tried to boot into the vm, but it didn't compile for some opengl reason, but it lead me to a realization. A while back, I took a C course, which involved me setting up global C flags via the CFLAGS variable. If I download a brand new version of the git repo, and unset my CFLAGS... It works. So, this is _somewhat_ my fault, but I think that fltk shouldn't build using the CFLAGS in the first place :) 
However, it appears that, when building for Release, the undefined reference errors will occur again. But they don't in debug if I have empty CFLAGS. Interesting.

**Comment by Albrecht-S** [comment]
@Explodey-Wolf Thanks for the answers and the confirmation. Please don't close the issue, I'll do this myself when the fix has been committed.

> I've never used CMAKE before, so I'm not sure what my default is, but it appears it's Debug.

No, the default is `undefined` (an empty string), this is a special CMake behavior - supposedly because this (cache) variable is not used in so-called multi-config builds like Visual Studio or Xcode IDE's. I suggest to use '-D CMAKE_BUILD_TYPE=...' always on the initial `CMake` commandline unless you configure a multi-config build.

> When I compiled with Release, it had an extra warning before the error ...

Different compiler switches and/or compiler checks depending on the build type may cause this. Can you please post the warning here too?

> I find it very odd that this only has occurred for me. I'll try running this in a vm and see if it has the same problem.

I don't know why this happened. Maybe something on your build system causes the `-fsanitize` flag to be added to the compiler command in general or it was caused by CMake for an unknown reason (or it was a build option of your compiler (gcc, g++, or clangg). Running in another VM would likely work, it's a good test. But finding out what caused this is OT here, although it's interesting, and if you can find the root cause, feel free to drop a note here, even if the issue has already been closed.

**Comment by Explodey-Wolf** [comment]
Well, that was good timing :)

**Comment by Explodey-Wolf** [comment]
The warning is the following. 
```
/home/wolf/fltk2/src/Fl_Help_View.cxx: In member function ‘void Fl_Help_View::follow_link(Fl_Help_Link*)’:
/home/wolf/fltk2/src/Fl_Help_View.cxx:2812:18: warning: ‘size_t strlcpy(char*, const char*, size_t)’ writing 4096 bytes into a region of size 2045 overflows the destination [-Wstringop-overflow=]
 2812 |           strlcpy(tempptr, linkp->filename, sizeof(temp));
      |           ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/wolf/fltk2/src/Fl_Help_View.cxx:49:
/home/wolf/fltk2/src/../FL/Fl_Help_View.H:228:17: note: at offset [3, 2048] into destination object ‘Fl_Help_View::directory_’ of size 2048
  228 |   char          directory_[FL_PATH_MAX];///< Directory for current file
      |                 ^~~~~~~~~~
In file included from /home/wolf/fltk2/src/../FL/Fl.H:47,
                 from /home/wolf/fltk2/src/../FL/Fl_Help_View.H:29:
/usr/include/string.h:506:15: note: in a call to function ‘size_t strlcpy(char*, const char*, size_t)’ declared with attribute ‘access (write_only, 1, 3)’
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
```

**Comment by Albrecht-S** [comment]
> The warning is the following...

Thanks, I've seen this myself some time ago and saved it for later exploration.

> I think that fltk shouldn't build using the CFLAGS in the first place :)

AFAICT there's nothing we do in our FLTK build regarding usage of `CFLAGS` and/or `CXXFLAGS` from the environment. This is disputable and has been discussed often. Some people say environment variables shouldn't be used for build system generation but - IIRC: from faint memory - the traditional `configure/make` build system does it as well.

See `CMake` docs: https://cmake.org/cmake/help/latest/envvar/CFLAGS.html

**Comment by Explodey-Wolf** [comment]
I'm pretty sure the trunc() function _is_ still a problem without my cflags(can't confirm), but overwriting the function probably works by default, which leads to the problem with only my cflags.

**Comment by Albrecht-S** [comment]
> I'm pretty sure the trunc() function is still a problem without my cflags ...

Hmm, interesting! Let me think about this...

It might indeed be that your `CFLAGS` setting caused the `check_function_exists()` call to fail because `CMake` tries to build and `link a program` to check this. If the build fails because of your wild `CFLAGS` settings the result would be 0 (FALSE).

Now you may ask "what about all the other 12 occurrences of `check_function_exists()`" ? Maybe they fail too but FLTK uses a fallback or am alternate function to work around this which is generally the purpose of such checks. Assumption: the only call that caused an error was that for `trunc()` because it generates a compiler error. I'm going to check that...

While I'm doing this, can you please "go back" to your FLTK 1.3 (`branch-1.3`) checkout and test whether it builds w/o your `CFLAGS` settings? Note that `CXXFLAGS`, `CPPFLAGS`, and `LDFLAGS` may be relevant as well: use `env | grep FLAGS` to check if your environment is clean. TIA.

**Comment by MoAlyousef** [comment]
@Explodey-Wolf what compiler are you using?

**Comment by Explodey-Wolf** [comment]
> @Explodey-Wolf what compiler are you using?

Clang.

**Comment by Explodey-Wolf** [comment]
> While I'm doing this, can you please "go back" to your FLTK 1.3 (branch-1.3) checkout and test whether it builds w/o your CFLAGS settings? Note that CXXFLAGS, CPPFLAGS, and LDFLAGS may be relevant as well: use env | grep FLAGS to check if your environment is clean. TIA.

It works.

**Comment by Albrecht-S** [comment]
Thanks for all the additional info. It's good to know that FLTK 1.3 works as well if CFLAGS is empty.

Meanwhile I built with `CFLAGS` and `CXXFLAGS` set (see below) with GCC:
```
$ /usr/bin/c++ --version
c++ (GCC) 14.2.1 20240805
```
The build succeeded, see the full log:
[build_with_CFLAGS_endeavour.txt](https://github.com/user-attachments/files/16740797/build_with_CFLAGS_endeavour.txt)

Maybe `clang` is another factor? I'll retry that too, just to find out what's going on (and for later user questions, of course).

**Comment by Explodey-Wolf** [comment]
Here are my cflags if you want them.
```
-fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wshadow
```

**Comment by Explodey-Wolf** [comment]
I'm also realizing now that the error I had in 1.4 most likely doesn't happen in 1.3 because the problem file, FL_TIMEOUT, does not exist in 1.3.

**Comment by Explodey-Wolf** [comment]
I rescind my previous statement about the truncation thing; HAVE_TRUNC is indeed defined as 1.

**Comment by Explodey-Wolf** [comment]
Also, the reason there was no other errors: According to my code, out of all the cxx files, only ONE of them checks if a defined variable is 1, then defines a function. And it's the HAVE_TRUNC one.

**Comment by Albrecht-S** [comment]
Ok, here are my final notes, I'm giving up to find the real cause, other than "some wild CFLAGS".

I built successfully with clang and the above mentioned CFLAGS and CXXFLAGS (`-fsanitize=undefined`).

@Explodey-Wolf I'm not going to try "your" CFLAGS because I spent already enough time on this issue.

@Explodey-Wolf One reason why any build failed with your CFLAGS given above is obviously `-Werror` which ["makes all warnings into errors"](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html). This may have been some (partially good) advice in your C course but this is only adequate if you have full control over your source code. You should never apply this to foreign code like a library you're building. Note that we (FLTK) try to remove (fix) **all warnings** we find but different compilers often add more warnings (notably Visual Studio), and sometimes you need to live with some warnings.

> I'm also realizing now that the error I had in 1.4 most likely doesn't happen in 1.3 because the problem file, FL_TIMEOUT, does not exist in 1.3.

The entire `HAVE_TRUNC` check is not implemented in 1.3 because it wasn't needed. It was added recently in `master` (1.4) to support some very old systems that had issues with `trunc()` being undefined.

**Comment by Explodey-Wolf** [comment]
Alright. @Albrecht-S , do you want me to close this issue? I've now changed my CFLAGS to be empty so I don't run into this problem again 🫡

**Comment by Albrecht-S** [comment]
I opened issue #1053 for the remaining part: "replace `check_function_exists()` with `check_symbol_exists()".`

Closing this issue now because it has been fixed.
