### ISSUE TITLE
Pressing backspace with a menu open causes FLTK programs to crash.

### ISSUE THREAD

**Issue by M0JXD** [fltk/fltk#1155]
**Describe the bug**
Pressing backspace with a menu open causes FLTK programs to crash.

I originally pointed this out in this project, the maintainer says the issue lies with FLTK.
https://github.com/Stazed/non-timeline-xt/issues/7#issue-2724637175

They say it sounds similar to this old issue: https://www.fltk.org/str.php?L1356

**To Reproduce**
I can reproduce this in the FLUID Designer.

1. Open the File Menu
2. Move the cursor outside the open menu
3. Press Backspace
4. Program crashes with Segmentation fault

**Expected behavior**
Program does not crash.

**FLTK Version**
 - Version: [e.g. 1.3.0]
 - Installed as package from: Linux Mint 22 Cinnamon

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Linux Mint 22 Cinnamon

**Linux/Unix Runtime, if applicable:**
 - X11

**Comment by dannye** [comment]
I don't see this bug on X11 with FLTK 1.3.10 or 1.4.0. Can you clarify which version of FLTK you are using?

The only oddity I see is that in 1.4.0 the "wrapping" doesn't work the same for backspace as it does for the left arrow key (which may or may not be intentional).
If holding backspace, the highlighted menu item moves to the very left and then stops (whereas it would wrap to the right for the left arrow key).
Then at this point, it takes _two_ right arrow presses to move the highlighted menu item once, which is odd.

**Comment by M0JXD** [comment]
The FLUID Designer version I have is 1.3.8 if that helps?
I'll try FLTK 1.4 and see if it persists.

**Comment by dannye** [comment]
I don't see the bug with FLTK 1.3.8 either.

**Comment by dannye** [comment]
Sorry, yes, I see the bug in 1.3.8 with both test/menubar and fluid. The crash only happens while the mouse is _not_ hovered over the menu.

But anyway, it appears to have been fixed since then, so there's probably nothing to do.

**Comment by M0JXD** [comment]
Thanks for confirming

I keep a Kubuntu VM running, I thought it'd be more up to date so I tried there.
The crash does occur of course but I have a different issue now, the iteration is still FLTK 1.3.8:

![Screenshot from 2024-12-08 16-09-15](https://github.com/user-attachments/assets/cde3ee8c-c849-4870-b33c-cabe64a7cc32)

This might be a wayland and/or VM issue.
So I still need to check 1.4, doh!

**Comment by erco77** [comment]
Yes, I can replicate the crash in the current 1.3.x from git.
Can't replicate in 1.4.x.

So whatever the fix is, perhaps could be back ported to a 1.3.x maintenance release.

**Comment by M0JXD** [comment]
Yes it does seem to be fixed already - I've just built FLTK from the master branch in my VM and the crash does not occur.

The display issue is still present in my VM though.
