### ISSUE TITLE
Keyboard sometimes stops working after Ctrl/+ or Ctrl/-

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#794]
**Describe the bug**
When using Ctrl/+ and Ctr/- sometimes the keyboard locks up and cannot be used any longer.

**To Reproduce**
I ran into this incidentally and have now tried a way to reproduce:
Use any of the test programs e.g. `hello`

- Hold down the Ctrl(Strg) key
- Hold down the '+' key and **do not** release it (this will kick keyboard repeat in)
- Let the '+' key held down until maximum zoom (300%) has been reached and **all the yellow overlay windows** with the zoom level **have disappeared**
- Finally release all keys

Now the keyboard is very often not functioning e.g. even the ESC-key will not work. Repeat procedure if necessary.

**FLTK Version**
1.4 git

**Operating System / Platform:**
Ubuntu 20.04

**Linux/Unix Runtime, if applicable:**
 - X11 or X11+Cairo

**Comment by Albrecht-S** [comment]
@wcout Thanks for the report. I don't see this here. I tried several (about 10) times with both X11 and Wayland backends.

**_Observation:_** (Slightly OT) Key repetition as suggested above doesn't work under the _Wayland backend_, presumably because the focus is moved to the "scale window" and not given back, or something like that. Key repetition works fine under the X11 backend but I don't see the reported issue.

**_Platform:_** Debian 12 / Bookworm with Gnome/Wayland session, i.e. **X11 programs using XWayland**. I can't test on a native X11 session right now,

**Comment by Albrecht-S** [comment]
I found another, probably related, issue on the Wayland platform when I tested with `test/twowin.cxx`. It may be related to the focus issue I reported above, and I apologize for potentially abusing this issue, but here it is anyway:

- run test/twowin (Wayland backend)
- click on one of the buttons b1 or b2 in the two windows slowly more than once
- after the second click the button sticks "down"
- after the next click it draws in the "up" position again
- this can be repeated as often as needed.

The same works fine under X11.

**Comment by wcout** [comment]
Some more information to my initial report:
It does *not* happen, when the transient scale display window is disabled (using fltk_options).

I put in some debug messages into Fl_x.cxx `fl_handle()`:

When the keyboard stops working at application level, this is always after a "XIM server has crashed" has happened (line Fl_x::1246) and subsequent keyboard events (which are delivered normally) now get rejected at line 1259:

````
  if (Fl_X11_Screen_Driver::xim_ic && XFilterEvent((XEvent *)&xevent, 0))
      return(1);
`````

**Comment by ManoloFLTK** [comment]
The other issue mentionned by @Albrecht-S  should be fixed with commit ded5839.

**Comment by Albrecht-S** [comment]
@ManoloFLTK Yep, works now AFAICT. Thanks and sorry for the noise.

@wcout Thanks for digging further into the issue. The message "XIM server has crashed" is a known issue that can happen (for whatever reason) but **if it happens** it **should** "fix itself" (IIRC). Unfortunately I'm not able to help with this, maybe @ManoloFLTK can ?

@wcout, can you tell us which "input method" (XIM) your system uses?

**Comment by ManoloFLTK** [comment]
I find that changing in `Fl_x.cxx` the code that runs when the "XIM server has crashed" as follows:
>       /*  XIM server has crashed */
>       XSetLocaleModifiers("");
>       Fl_X11_Screen_Driver::xim_im = NULL;
>       Fl_X11_Screen_Driver::init_xim();
>       if (Fl_X11_Screen_Driver::xim_win && Fl_X11_Screen_Driver::xim_win != xid) {//new
>         Fl_X11_Screen_Driver::xim_deactivate();//new
>       }//new

that is, adding the last 3 lines shown above, fixes the issue.

@wcout Is it what you observe too?

@Albrecht-S Do you see any reason to expect adverse effects from this modified code?

**Comment by wcout** [comment]
@ManoloFLTK I will try your proposed fix within a few days.

**Comment by Albrecht-S** [comment]
> @Albrecht-S Do you see any reason to expect adverse effects from this modified code?

Sorry, I can't help. I remember that there were issues with "dying" XIM servers but I have no idea what is right or wrong here.

**Comment by wcout** [comment]
> I find that changing in Fl_x.cxx the code that runs when the "XIM server has crashed" as follows:
      /*  XIM server has crashed */
      XSetLocaleModifiers("");
      Fl_X11_Screen_Driver::xim_im = NULL;
      Fl_X11_Screen_Driver::init_xim();
      if (Fl_X11_Screen_Driver::xim_win && Fl_X11_Screen_Driver::xim_win != xid) {//new
        Fl_X11_Screen_Driver::xim_deactivate();//new
      }//new
that is, adding the last 3 lines shown above, fixes the issue.
@wcout Is it what you observe too?

I can confirm that with this change I am not able to produce any keyboard locks any more. So it seems to fix the issue.

**Comment by ManoloFLTK** [comment]
@wcout  The commit above (c1d9376) should bring some improvement. What do you observe?

**Comment by wcout** [comment]
Sorry, I don't see an improvement regarding this issue.

One other notice: I am testing with `test/input` and when the keyboard "locks up" (i.e. Ctrl+/Ctrl/- stop working and no input into the text fields is possible) it can be unlocked by clicking the "color" button, which brings up the color chooser. After that the keyboard works again.

**Comment by wcout** [comment]
BTW: Why is the transient window display coded in a way that multiple windows can exist simultaneously? It seems overcomplicated for me and also looks a little strange at downscaling. But perhaps I am missing something.

But out of couriosity I tried to display only one window at a time by hacking the code:

````diff
diff --git a/src/Fl_Screen_Driver.cxx b/src/Fl_Screen_Driver.cxx
index a98577e19..49684a743 100644
--- a/src/Fl_Screen_Driver.cxx
+++ b/src/Fl_Screen_Driver.cxx
@@ -398,7 +398,8 @@ static void del_transient_window(WinAndTracker *data) {
     }
     delete data->tracker;
   }
-  delete data;
+  data->win = 0;
+  data->tracker = 0;
 }
 
 void Fl_Screen_Driver::transient_scale_display(float f, int nscreen)
@@ -441,12 +442,15 @@ void Fl_Screen_Driver::transient_scale_display(float f, int nscreen)
   win->set_non_modal();
   Fl_Window_Driver::driver(win)->screen_num(nscreen);
   Fl_Window_Driver::driver(win)->force_position(1);
-  WinAndTracker *data = new WinAndTracker;
-  data->win = win;
+  static WinAndTracker data = {0, 0};
+  if (data.win)
+    del_transient_window(&data);
+  data.win = win;
   Fl_Widget *widget = Fl::focus();
-  data->tracker = (widget ? new Fl_Widget_Tracker(widget) : NULL);
+  data.tracker = (widget ? new Fl_Widget_Tracker(widget) : NULL);
   win->show();
-  Fl::add_timeout(1, (Fl_Timeout_Handler)del_transient_window, data); // delete after 1 sec
+  Fl::remove_timeout((Fl_Timeout_Handler)del_transient_window, &data);
+  Fl::add_timeout(1, (Fl_Timeout_Handler)del_transient_window, &data); // delete after 1 sec
   win->wait_for_expose();
   Fl::flush();
   Fl::check();
````
Interestingly I could not produce the keyboard lockup with this change.

**Comment by ManoloFLTK** [comment]
@wcout Thanks. I've followed another route and believe to have a fix with the last commit. Can you confirm?

**Comment by wcout** [comment]
Yes, that is good. I could not produce any keyboard lock-ups with it now.
So out of interest: What was the reason for this problem in your view?

**Comment by ManoloFLTK** [comment]
Unfortunately, I could not pin down the exact reason of this issue. It's an extreme situation where X11 and X Input Methods have to rapidly create windows, close and re-create input contexts and dismiss windows. For some reason, the issue disappears when transient windows are made subwindows of a parent.

**Comment by wcout** [comment]
Some after-thoughts...

**Note 1:**
I think I now found the culprit for the original issue:

In `src/Fl_Screen_Driver.cxx` the deletion of the transient window

````cxx
static void `del_transient_window(WinAndTracker *data)` {
  delete (Fl_Image*)data->win->shape();
  Fl::delete_widget(data->win);
  if (data->tracker) {
    if (data->tracker->exists()) {
      Fl::focus(data->tracker->widget());
      data->tracker->widget()->handle(FL_FOCUS);
    }
    delete data->tracker;
  }
  delete data;
}
````
the code for restoring the focus is IMHO not optimal (it does too much),
````cxx
      Fl::focus(data->tracker->widget());
      data->tracker->widget()->handle(FL_FOCUS);
````
and might be better replaced by:

````cxx
      data->tracker->widget()->take_focus();
````

At least with this change I can not produce the issue with the **original code** before the fix.

**Note 2:**
As the transient scale window is added to the current top window, this may lead to some unexpected results:

1) The top window might be deleted or its children be removed by the application during the scale display is on the screen. This will then crash FLTK when it tries to delete the scale window. That could  be provided for however, by using a Widget-Tracker for the window too.

2) The application may have problems if it is dynamically processing the child widgets in its group, not expecting a new widget has been injected into its child list.

Don't know how likely this all is ... but think of an application that displays some real time data by dynamically creating and deleting child widgets in its window with a short periodic timer.

Perhaps the original version of the scale display as an own window should still be preferred (if the change in Note 1 really helps). Though I see that the Wayland driver already had the "add to top window" approach for some reason...

**Comment by Albrecht-S** [comment]
@wcout Thank you again for your continued code review and analysis. We appreciate this very much.

@ManoloFLTK Since FLTK 1.4 we should not need `Fl::delete_widget(data->win);` anymore. This should be replaced by simply deleting the widget: `delete data->win;`.

Note: if there is really a case where just `delete` would crash the application, then this would be a bug elsewhere and should be investigated.

I also agree with Chris that `data->tracker->widget()->take_focus();` would be the better instruction here. ISTR that this is indeed documented somewhere.

And after all, I didn't exactly follow the changes regarding this issue. But if the current (i.e. modified) code injects the scale display window into the user's top window, then I agree with his statements above and vote to try hard to avoid this. There could be any number of unwanted (side) effects if we change the user's widget arrangements - if I understood correctly what he was saying and what the current code does.

Note: I'm reopening this issue so this discussion doesn't get lost

**Comment by ManoloFLTK** [comment]
@wcout Many thanks for finding how to remove those problems with input methods while keeping the transient window centered on the display. The fix is now committed.

@Albrecht-S Unless another approach is found, the transient scale window remains a centered child of the top window under Wayland because Wayland gives no way to position a window inside a display, and worse, not even to send a window on a desired display when the system contains multiple displays. The only control Wayland gives a client app is to choose on what display to map a fullscreen window.

I see that I had not found the adequate way to give focus to a widget in the documentation which ultimately resulted in this issue. I've therefore tried to improve the documentation of `Fl::focus(Fl_Widget*)`. Please, review that.

**Comment by Albrecht-S** [comment]
> Unless another approach is found, the transient scale window remains a centered child of the top window under Wayland ...

@ManoloFLTK I wonder how menu windows are positioned under Wayland. I don't think they are added as child windows, are they? If not, could we use the same technique to center the scale window over the current top window?

> I've therefore tried to improve the documentation of Fl::focus(Fl_Widget*). Please, review that.

Your wording is maybe a bit misleading although it is not totally wrong. It seems to imply that a widget should call `Fl::focus()` when it receives the `FL_FOCUS` event but usually a widget wouldn't **need** to call this. Our [documentation of FL_FOCUS](https://www.fltk.org/doc-1.4/events.html#events_fl_focus) states:

> "If a widget wants the focus, it should change itself to display the fact that it has the focus, and return non-zero from its handle() method. It then becomes the [Fl::focus()](https://www.fltk.org/doc-1.4/group__fl__events.html#ga38b004e3a0aaf3d122b1676817a9cc30) widget and gets FL_KEYDOWN, FL_KEYUP, and FL_UNFOCUS events."

This means that the widget ["automagically"] **becomes** the `Fl::focus()` widget **w/o itself calling** `Fl::focus(this)`. Actually the latter is done in `Fl_Widget::take_focus()` if (and only if) the widget returned 1.

Looking through our code it seems that the only true reason to call `Fl::focus(this)` is the `FL_PUSH` event, i.e. if an input widget that wants to handle keyboard events receives `FL_PUSH`. As always there are some exceptions from this rule in the code, at least one or two are looking questionable and should maybe be fixed. I'll check that.

Sorry if this looks like nitpicking. What do you think, should I try to improve the wording and add more details?

**Comment by wcout** [comment]
> @ManoloFLTK I wonder how menu windows are positioned under Wayland. I don't think they are added as child windows, are they? If not, could we use the same technique to center the scale window over the current top window?

Good idea! I think that may work. Not as menu, but as tooltip!

As a proof I tried a quick hack:

````diff
diff --git a/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx b/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx
index 07bb5230d..33cf02ccf 100644
--- a/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx
+++ b/src/drivers/Wayland/Fl_Wayland_Window_Driver.cxx
@@ -1376,10 +1376,11 @@ void Fl_Wayland_Window_Driver::makeWindow()
   if (pWindow->user_data() == &Fl_Screen_Driver::transient_scale_display &&
       Fl::first_window()) {
   // put transient scale win at center of top window by making it a child of top
+    pWindow->set_tooltip_window();
     int center_x, center_y;
     Fl_Window *top = calc_transient_parent(center_x, center_y);
     if (top) {
-      top->add(pWindow);
+//      top->add(pWindow);
       pWindow->position(center_x - pWindow->w()/2 ,  center_y - pWindow->h()/2);
     }
   }

````

The scaling window is now displayed as a tooltip, **not** adding a child to the top window.
Seems to work. Not perfect because multiple instances are created, but that was only for proof...

**Comment by Albrecht-S** [comment]
@wcout Thanks for testing.

@ManoloFLTK Another idea I had was to keep the scaling window "hanging around" once it has been created. We could just show/hide it and always "edit" the scaling factor in an "update_scaling_factor" function or so. This function would have to remove and re-add the timer whenever it's shown.

This would simplify the code (IMHO) and avoid having multiple scaling displays on top of each other, as it is now.

For the user the window would pop up once, and whenever they hit ctrl/+/- again, it changes the scaling factor and stays alive for another second or whatever the timer may be.

At least it's an idea, and together with the "tooltip window POC" by Chris, I'd think that this should work.

Manolo?

**Comment by ManoloFLTK** [comment]
I'm successfuly redesigning the transient window as a popup under Wayland. 

The plan of keeping a unique transient window alive can't work under Wayland because any popup needs a parent window and that parent is subject to constant changes.

@Albrecht-S Please, feel free to rewrite/complete the documentation of `Fl::focus(Fl_Widget*)`.

**Comment by Albrecht-S** [comment]
OK, thanks. Looking forward to your solution.

I'll check the docs...

**Comment by wcout** [comment]
@ManoloFLTK 
There are some issues with the recent changes:
1. The last commit removed the deletion of the shape() image when the window is deleted (leak)
2. Under Wayland applications with subwindows crash when they are re-scaled
3. Under Wayland there is Wayland "fatal error" when ESC is pressed while the transient scale window is shown

I have fixed them here:
[transient_fixes.diff.txt](https://github.com/fltk/fltk/files/13072830/transient_fixes.diff.txt)

Note: The fix for 3. is perhaps not very elegant due to my lack of knowledge about the Wayland internals ... it is only for demonstration ;)

**Comment by Albrecht-S** [comment]
Reopening again.

@wcout Thanks for testing and for the potential fix.

@ManoloFLTK  thanks for your continued work on this issue - but please wait before closing this issue until it has been confirmed to work.

**Comment by ManoloFLTK** [comment]
@wcout Thanks for your fix proposal.

Commit 3868ea9 should fix most issues, but there's still a problem with the editor demo, 2 windows, hitting Escape when a transient window is shown. Still working.

**Comment by wcout** [comment]
@ManoloFLTK Regarding your fix for 3.: I had just a short look into your changes .. so I am no sure ...but it seems you simply don't hide() the window, when a popup is still displayed.
But what if an application wants to exit by hiding its window in this time? It will then not exit as planned. Is this not a potential regression?

**Comment by ManoloFLTK** [comment]
@wcout  All my tests went OK with commit 0636c0b. Please, report here what you find.

**Comment by wcout** [comment]
@ManoloFLTK With the current version the initial issue and all intermediate issues are resolved. You may close the issue .. but read on, if you think a minor problem I discovered with this version should be resolved.

When I tested using the recipe described in the initial report (Repeating key on X11) I found, that now once so often it happens that it changes the scaling in the console where I started the FLTK program (because the console window also reacts to Ctrl/+, Ctrl-).

I believe this is because the focus handling has been removed now **and** the old previous transient window is deleted first and then the new one is shown. During this change the console window may gain keyboard focus again and process the zoom shortcut.

So i think it would be better to **first** show the new transient window and **afterwards** delete the previous one.
But on Wayland this will then lead to the problem with correct order of deletion, so this has to be worked around.

I tried the following change here and it seems to resolve the "focus to console" problem:
[optim_trans.diff.txt](https://github.com/fltk/fltk/files/13161236/optim_trans.diff.txt)

You may consider that or close the issue, it is not a big problem ... just annoying.
