### ISSUE TITLE
`FL_SHORTCUT` and `FL_KEYBOARD` do not honor `FL_WHEN_RELEASE` for `FL_RADIO_BUTTON`

### ISSUE THREAD

**Issue by dannye** [fltk/fltk#877]
**Describe the bug**

The description for `FL_WHEN_RELEASE` is:

> FL_WHEN_RELEASE           =  4, ///< Do the callback when the button or key is released and the value changes

However, a key down event for the shortcut (`FL_SHORTCUT`) or spacebar on a focused widget (`FL_KEYBOARD`) will trigger the callback, even when the radio button is already set and `when_` is `FL_WHEN_RELEASE`. This is notably different from a mouse button release (`FL_RELEASE`), which will _not_ invoke the callback if the radio button is already set.

The actual behavior is more like what I would expect for if `when_` is set to `FL_WHEN_RELEASE_ALWAYS`.

**Additionally**: Astonishingly, `FL_SHORTCUT` <ins>never</ins> calls `set_changed()` and `FL_KEYBOARD` <ins>always</ins> calls `set_changed()` (in `Fl_Button::handle()`), regardless of whether the radio button value is changing or not. This thwarts any possibility of checking `if (button->changed())` in the callback to decide whether to run the rest of the callback or not.

Also, holding down the spacebar on a focused radio button invokes the callback on each repeat. Of course, if the callback was only invoked on value change, then this issue would "fix itself".

All of this together means it's unreasonably difficult to create a radio button that only invokes its callback _on change_, which is what `FL_WHEN_RELEASE` is intended for, afaict.

In order to work around this, one would either need to subclass to override `handle()` in order to return early if the radio button is already set:

```cpp
if ((event == FL_SHORTCUT || event == FL_KEYBOARD) && value()) {
	return 0;
}
```

or one would need to store some separate/redundant state to manually track radio button changes to know when the full callback should be executed.

Both of these workarounds seem non-ideal.

**To Reproduce**

This can be witnessed in the default test program, radio.cxx.

However, here is an alternate radio.cxx with a more practical example that demonstrates why having better control over only invoking the callback on change would be advantageous:

<details>

<summary>radio.cxx</summary>

```cpp
#include "radio.h"

#include <FL/Fl_Int_Input.H>

#include <string>

Fl_Int_Input *int_input=(Fl_Int_Input *)0;

static void inches_radio_button_cb(Fl_Button *b, void *) {
  std::string val = std::to_string(std::atoi(int_input->value()) * 12);
  int_input->value(val.c_str());
}

static void feet_radio_button_cb(Fl_Button *b, void *) {
  std::string val = std::to_string(std::atoi(int_input->value()) / 12);
  int_input->value(val.c_str());
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(300, 100);
    w = o; (void)w;
    { Fl_Int_Input* o = new Fl_Int_Input(80, 10, 150, 30, "Length");
      o->value("72");
      int_input = o;
    } // Fl_Int_Input* o
    { Fl_Round_Button* o = new Fl_Round_Button(10, 40, 70, 30, "&inches");
      o->type(FL_RADIO_BUTTON);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->when(FL_WHEN_RELEASE);
      o->callback((Fl_Callback*) inches_radio_button_cb);
      o->set();
    } // Fl_Round_Button* o
    { Fl_Round_Button* o = new Fl_Round_Button(80, 40, 70, 30, "&feet");
      o->type(FL_RADIO_BUTTON);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->when(FL_WHEN_RELEASE);
      o->callback((Fl_Callback*) feet_radio_button_cb);
    } // Fl_Round_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
```

</details>

1. Replace test/radio.cxx with the above^ radio.cxx
2. Run `make`
3. Run `./test/radio`
4. Notice that using the mouse to switch between inches and feet works as expected (doesn't invoke the callback on repeated clicks)
5. Notice that using the shortcuts "i" and "f" disregards the current state of the radio buttons and always invokes the callback
6. Notice that using the spacebar to "click" the focused button also always invokes the callback

**Expected behavior**
`FL_SHORTCUT` and `FL_KEYBOARD` should behave more like `FL_RELEASE` with regard to `FL_RADIO_BUTTON`s with `FL_WHEN_RELEASE` with respect to when to `do_callback()`.

**Video**

https://github.com/fltk/fltk/assets/5231310/ba8b8ace-370b-4f8a-9294-fdb6449e3703

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.4.0
 - Downloaded and self-built from: Git
 - If from Git, branch: master
 - If from Git, commit: 1d73c01

**FLTK Configure / Build Options**
Please add the complete configure and build command lines if you built FLTK yourself.
Please include all configure or CMake options and add all CMake options you changed
by using CMake GUI tools (if any).
 - `make`

**Operating System / Platform:**
Please be as precise as possible, e.g. "Linux: Ubuntu 20.04"
 - OS: Linux
 - OS Version: PeppermintOS 10

**Additional context**
Merry Christmas :)

**Comment by MatthiasWM** [comment]
Thanks for finding this and taking the time to write this Issue report. There is also incorrect testing of `wp.deleted()` in some cases. I will try to take a look at this in the next days.

**Comment by dannye** [comment]
Thanks!

For the record, I didn't do any thinking about wether handling of `FL_SHORTCUT`/`FL_KEYBOARD` is or is not ideal for button types other than `FL_RADIO_BUTTON` or `when_`s other than `FL_WHEN_RELEASE`.

**Comment by MatthiasWM** [comment]
Please check the behavior of Fl_Button with the code that I committed. I added much more detailed information on the when() flags in the Fl_Button constructor, hoping it makes more sense now.

To all core devs, I had to rewrite the logic a little bit, hoping that I did not create any surprising behavior. some of the original logic was off, and, as the Issue here describes, not consistent between mouse and keyboard handling.

**Comment by Albrecht-S** [comment]
@MatthiasWM Please see my comments on commit 826eb39d687ae499119c0ed1b7b0e4d60c314e62 for a few issues. Particularly the one about using a static variable in handle() across events which should IMHO be avoided, regardless whether or not it can do harm in the current code. I suggest to store this state info in a member variable.

**Comment by MatthiasWM** [comment]
Sorry, the last two commits were for #887, not #877

**Comment by dannye** [comment]
@MatthiasWM Unfortunately, commit 826eb39 does not fix the bug that I am reporting -- which is that repeatedly pressing the shortcut key or spacebar will repeatedly invoke the callback on an already-selected radio button.

The commit also introduces a new bug, which is that repeated mouse clicks now incorrectly repeatedly invoke the callback on an already-selected radio button -- which was not an issue previously. [1]

The only minor bug that appears to be fixed is:

> Also, holding down the spacebar on a focused radio button invokes the callback on each repeat.

However, in fixing this, 2 additional bugs were introduced. (1) Holding down the shortcut key, or (2) holding down the spacebar, now no longer repeatedly invokes the callback on _non_ radio buttons [2].

@MatthiasWM @Albrecht-S Regarding the static variable `s_key_repeat`; I propose that no static variable is needed whatsoever.

As I wrote in the OP:

> Also, holding down the spacebar on a focused radio button invokes the callback on each repeat. _Of course, if the callback was only invoked on value change, then this issue would "fix itself"._

The introduction of the static variable was only to fix repeats, but repeats would be fixed for radio buttons anyway if the primary bug was fixed first.
And repeats are actually desirable for non radio buttons, so the static variable may not serve any purpose. Although, maybe you could argue that certain `when_` values could benefit from such a static variable to detect repeats; I haven't though enough about it. But I don't believe that a typical non radio button or a typical radio button needs the static variable.

---

[1] Video of the same radio.cxx program provided in the OP compiled with commit 826eb39:

https://github.com/fltk/fltk/assets/5231310/bb496c0d-00d9-4909-ba90-52f0137606a9

[2] I argue that invoking the callback on every repeat for _non_ radio buttons (which was existing behavior prior to commit 826eb39) is actually desirable.
For example, consider how I take advantage of repeats by holding down the shortcut key to trigger a button repeatedly (it would be tedious and unnecessary to require the user to press the shortcut over and over for a button which was designed to be pressed repeatedly, ie. a non radio button):

https://github.com/fltk/fltk/assets/5231310/31397902-cb48-43e5-b67c-11e5264b5a66

**Comment by Albrecht-S** [comment]
> Regarding the static variable s_key_repeat; I propose that no static variable is needed whatsoever.

@dannye OK, I think I can follow you.
1. Normal buttons should repeat when keys are pressed (and held). This is IMHO the desired behavior.
2. Radio buttons should probably never repeat, i.e. when their state is ON and you click them, the callback should not be invoked. I'm not sure if **_any_** `when()` condition should change this (maybe `FL_WHEN_NOT_CHANGED` should repeat no matter if the value changed?). There's a precedence in `Fl_Tabs` (not verified, I just saw it's used there).
3. I can't see in your video(s) if you wanted a button to repeat when a mouse button is clicked and held. This would involve a timer (like in scrollbars IIRC) and would IMHO be OT here.

Is my summary correct? If yes I assume that no static variable would be necessary - as you suggest - because the radio button state would serve as a flag to decide whether the button should trigger a callback - maybe dependent on a certain `when()` condition or not.

@MatthiasWM What do you think? My summary/conclusion above may not be complete, you may know more about the current (and previous) code and I may be missing something.

**Comment by Albrecht-S** [comment]
@dannye Please post your (short and simple) `radio-callback` example code (the one with "inches" and "feet") so we can easier test. Also, if your project `Crystal Tracker` is public, can you please post a link? It's sometimes much easier to work on the FLTK library if you can test with "real" code.

**Comment by dannye** [comment]
> 2\. I'm not sure if **_any_** `when()` condition should change this (maybe `FL_WHEN_NOT_CHANGED` should repeat no matter if the value changed?).

I also think `FL_WHEN_RELEASE_ALWAYS` should possibly invoke the callback on an already-selected radio button. (Both for the mouse button release as well as shortcut/keyboard.)

> 3\. I can't see in your video(s) if you wanted a button to repeat when a mouse button is clicked and held.

No, that is not my intention. I don't expect any repeats via the mouse buttons.

> Please post your (short and simple) `radio-callback` example code (the one with "inches" and "feet") so we can easier test.

The source code for my custom example was included in the OP.

> Also, if your project `Crystal Tracker` is public, can you please post a link? It's sometimes much easier to work on the FLTK library if you can test with "real" code.

Yes: https://github.com/dannye/crystal-tracker

@Albrecht-S

**Comment by Albrecht-S** [comment]
> The source code for my custom example was included in the OP.

Ah, yes, sorry, I missed this because it's "hidden" under the `<details>` stuff when I searched for a link or whatever.

I took a look at your `crystal-tracker` project but this seems to be too much to build as a test program (for me). Thanks anyway.

**Comment by MatthiasWM** [comment]
Ok, I will reverse my changes at this point. Some if it was meant well, but introduces too many changes in the existing system, I will instead apply the bare minimum to fix the original issues and leave it at that.

**Comment by MatthiasWM** [comment]
@dannye I rewrote my fix from scratch, trying to not change mouse click callback while duplicating the button behavior for key presses and keyboard shortcuts. Please let me know if it behaves as expected now.

**Comment by Albrecht-S** [comment]
@MatthiasWM Did I miss your commit/push, or did you forget to push it? I'm only seeing
Commit a038e557835a0b1e8700c53f267043856f22055f "Restore original Fl_Button event behavior(#877)"

**Comment by dannye** [comment]
Without looking at the code changes, I can confirm the mouse+keyboard behavior for radio buttons is exactly as expected for both the original test/radio and and my custom test program, even for non-default `when_`s of `FL_WHEN_RELEASE_ALWAYS` or `FL_WHEN_NOT_CHANGED`.

Thanks!

**Comment by Albrecht-S** [comment]
@dannye Thanks for confirmation. Closing the issue now.
