### ISSUE TITLE
Wayland: numeric keypad keys don't work as intended when NumLock is off

### ISSUE THREAD

**Issue by Albrecht-S** [fltk/fltk#881]
I apologize for the terse report and description:

Under Wayland numeric keypad keys work well if NumLock is ON but return unexpected values otherwise.

To reproduce: use `test/keyboard.cxx` and/or `examples/howto-remap-numpad-keyboard-keys.cxx`:

- `test/keyboard` returns bogus values when NumLock is off
- `examples/howto-remap-numpad-keyboard-keys` doesn't work if the check button `"Force numeric keypad to type numbers"` is on and `NumLock` is off.

FLTK version: Git current (master).

@ManoloFLTK I'm assigning this one to you, hope you don't mind.

**Comment by Albrecht-S** [comment]
`Prio 3 - Moderate` because this is an essential feature but not really high priority (it affects only a special usage) on one platform.

I'm also adding it to the release milestone: should be fixed in 1.4.0.

**Comment by Albrecht-S** [comment]
I forgot to mention: the wrong results are obviously caused by `Fl::event_original_key()` under Wayland not working correctly if NumLock is off.

**Comment by ManoloFLTK** [comment]
@Albrecht-S test/keyboard is fixed with the above commit. Is everything OK?

**Comment by Albrecht-S** [comment]
@ManoloFLTK No, unfortunately not.

1. The `','` (German) or `'.'` (English) keys on the keypad should send FL_Delete when NumLock is off (it sends `FL_KP+'^_'). This should be only one more line where you fixed the other keys in the recent commit.

2. `Fl::event_original_key()` still doesn't return the correct value. This can be seen in the demo program `examples/howto-remap-numpad-keyboard-keys.cxx`.

Note: `examples/howto-remap-numpad-keyboard-keys.cxx` lacks a display to let the user know the current NumLock state. I don't have a visible indication of the NumLock state on my notebook which means it's hard to test and to describe what's wrong.

I'm working on more detailed output in `test/handle_events.cxx` so this can be tested better. I'll let you know here when I committed an update.

**Comment by ManoloFLTK** [comment]
@Albrecht-S With commit e1cd6de, the ./, key and `Fl::event_original_key()` should be OK.

**Comment by Albrecht-S** [comment]
> With commit https://github.com/fltk/fltk/commit/e1cd6dec4a6ada7f5591271ec9e19cff1749bdcf, the ./, key and Fl::event_original_key() should be OK.

Yep, thanks, but there was still one key missing. Added in commit 37eefe554888c240df85c4fdf17d24fc368cd11d.

FTR: There was also an inconsistency in the demo program `examples/howto-remap-numpad-keyboard-keys.cxx`: this demo didn't overwrite `Fl::e_keysym` when it translated the original keysym to the correct text (`Fl::e_text`). This caused an issue under Wayland because some input widgets use `Fl::e_keysym` for input processing - maybe erroneously. I'm not sure why this happens on Wayland but not on X11, this might be worth another investigation.
Anyway, fixed in 829cac52c63bfb0b9ec87a36a586f4956a55624d.

@ManoloFLTK Thanks for your fixes. Together with mine this issue is resolved AFAICT. Closing now.

**Comment by ManoloFLTK** [comment]
>> With commit https://github.com/fltk/fltk/commit/e1cd6dec4a6ada7f5591271ec9e19cff1749bdcf, the ./, key and Fl::event_original_key() should be OK.
> 
> Yep, thanks, but there was still one key missing. Added in commit https://github.com/fltk/fltk/commit/37eefe554888c240df85c4fdf17d24fc368cd11d.

@Albrecht-S  I had purposefuly excluded the "./," key from the 2nd table because I see it having the correct `e_original_keysym` value without extra processsing. But, having that key in both tables allows us to use one `if` statement only. I've committed this (2db1929).

**Comment by Albrecht-S** [comment]
> I had purposefuly excluded the "./," key from the 2nd table because I see it having the correct e_original_keysym value without extra processsing.

@ManoloFLTK I noticed that had added and removed it later, before I added it again because it didn't work w/o it for me.

> having that key in both tables allows us to use one if statement only. I've committed this ...

I noticed this too, OK.

I was tempted to use symbolic names instead of hex codes but I decided it wouldn't be worth the effort. Another thought was to use one table with both values per entry (a struct of two members), but again, not worth the effort, IMHO. Unless we need to change it for any other reason or for clarity.

One point remains questionable though: I see that both X11 and Wayland send `0xffac` which is good because it's consistent. However, this is equivalent to `FL_KP + ','` (comma) which produces the correct result on my German keybord but seems wrong for other (English, American) keyboards. I couldn't figure out what would happen with an English keyboard on my system. Just changing the keyboard to 'en' didn't work, even in a terminal program (although it worked for other keys on the main keyboard), hence I gave up: it's always been this way (on X11), and maybe it works by using another level of X11 settings to convert this if set up correctly? I don't know and I won't pursue this.
