### ISSUE TITLE
PVS-studio static analyzer issues 

### ISSUE THREAD

**Issue by shlyakpavel** [fltk/fltk#9]
I have already left an issue on clang-tidy. Now it's time for a more advanced tool. I have copied here only the places I personally suspect to be wrong. However, it would be much better if someone performed a full code check with this tool on a regular basis.
1. I believe a `break` is missing here.
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl.cxx#L1308
2. Same here
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Input_.cxx#L1012
3. The 'first' local variable possesses the same name as one of the class members, which can result in a confusion.
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Browser.cxx#L514
4. Pointer to local array 'fixpath' is stored outside the scope of this array. Such a pointer will become invalid.
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_File_Chooser2.cxx#L455
5. Expression 'menu' on line 536 is always true as it was checked on line 530
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Menu.cxx#L530-L536
6. Why?
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Text_Buffer.cxx#L1251
It is same to `mGapStart = start` but much harder to read and understand
7. Just perfect :D
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver.cxx#L175-L176
I guess it needs refactoring
8. Condition `n > 2` is always true https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_vertex.cxx#L55-L59
Same here:
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_vertex.cxx#L38-L42
And here:
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_vertex.cxx#L78-L83
9. This make a lot of the following code useless
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_x.cxx#L517
10. The 'prop' pointer was utilized before it was verified against nullptr. The code is strange. The condition should be probably like `if (*prop)`
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_x.cxx#L1202-L1204
Same here
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_x.cxx#L2222-L2223
11. In this FL_Froup_Type.cxx `live_widget` is always tested against null pointer. However, that makes no sense as the memory was allocated with the new operator
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/fluid/Fl_Group_Type.cxx#L338-L340
You can find the same places inside the file on lines 355, 371, 399
12. Nonsense
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/fluid/Fl_Menu_Type.cxx#L363
https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/fluid/Fl_Menu_Type.cxx#L369
There are a lot of warnings generated (1413). I will leave some extra comments later :)
Thanks for working on such a great library! Have a nice day!

**Comment by MatthiasWM** [comment]
> On Dec 27, 2018, at 12:05, Pavel Shlyak <notifications@github.com> wrote:
> 
> I have already left an issue on clang-tidy. Now it's time for a more advanced tool. I have copied here only the places I personally suspect to be wrong. However, it would be much better if someone performed a full code check with this tool on a regular basis.
> 
> 	• I believe a break is missing here.
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl.cxx#L1308

Intentional.

> 	• Same here
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Input_.cxx#L1012

Intentional.

> 	• The 'first' local variable possesses the same name as one of the class members, which can result in a confusion.
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Browser.cxx#L514

Fixed.

> 	• Pointer to local array 'fixpath' is stored outside the scope of this array. Such a pointer will become invalid.
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_File_Chooser2.cxx#L455

Actual bug. Good catch. Fixed.

> 	• Expression 'menu' on line 536 is always true as it was checked on line 530
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Menu.cxx#L530-L536

Line 530 was added later and made the test in 536 obsolete. Fixed.

> 	• Why?
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_Text_Buffer.cxx#L1251
> It is same to mGapStart = start but much harder to read and understand

True. Fixed.

> 	• Just perfect :D
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver.cxx#L175-L176
> I guess it needs refactoring

Because the XFT support is not complete yet? But I am not on X, so I will not touch the Xlib driver code... .

> 	• Condition n > 2 is always true https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_vertex.cxx#L55-L59
> Same here:
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_vertex.cxx#L38-L42
> And here:
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/drivers/Xlib/Fl_Xlib_Graphics_Driver_vertex.cxx#L78-L83
> 	• This make a lot of the following code useless
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_x.cxx#L517
> 	• The 'prop' pointer was utilized before it was verified against nullptr. The code is strange. The condition should be probably like if (*prop)
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_x.cxx#L1202-L1204
> Same here
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/src/Fl_x.cxx#L2222-L2223

> 	• In this FL_Froup_Type.cxx live_widget is always tested against null pointer. However, that makes no sense as the memory was allocated with the new operator
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/fluid/Fl_Group_Type.cxx#L338-L340
> You can find the same places inside the file on lines 355, 371, 399

True. This code is centuries old, and I wrote it in times when it was not clear (at least to me ;-) if 'new' could return NULL. Fixed.

> 	• Nonsense
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/fluid/Fl_Menu_Type.cxx#L363
> https://github.com/fltk/fltk/blob/5c7118f8d9a4a89742c33d411e5f207b9108b32e/fluid/Fl_Menu_Type.cxx#L369

Yeah, but not really a drama, is it. The first 'if' should be optimized away by the compiler. Anyway, I refactored it.

> There are a lot of warnings generated (1413). I will leave some extra comments later :)
> Thanks for working on such a great library! Have a nice day!
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Mit freundlichen Grüssen,

 Matthias Melcher

---
Geschäftsführer

M.Melcher GmbH
Hohenbudberger Strasse 4-10
47829 Krefeld Uerdingen

m.melcher@goebels-melcher.de

Fon +49 2151 4832 26
Fax +49 2151 4832 38

**Comment by MatthiasWM** [comment]
> On Dec 27, 2018, at 12:50, Pavel Shlyak <notifications@github.com> wrote:
> 
> As for 1, it's probably not a mistake. If so, consider marking such places with a special attribute in the future
> https://en.cppreference.com/w/cpp/language/attributes/fallthrough
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Well, we will not support C++17 or any of its attributes any time soon. I did mark the // fALLTHROUGH which many compilers recognize.

**Comment by shlyakpavel** [comment]
@MatthiasWM thanks a lot for your quick response!
I have some more points here:
13. Dereferencing of the null pointer 'past' might take place.
https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/src/gl_draw.cxx#L109
14. The size of the allocated memory buffer is not a multiple of the element size. I guess it's intentional, but it still doesn't seem to be safe.
https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/src/Fl_JPEG_Image.cxx#L259
15. An object is used as an argument to its own method. Consider checking the first actual argument of the 'hotspot' function.
https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/fluid/about_panel.cxx#L271
This one was added by https://github.com/fltk/fltk/commit/3ef18e4b7dbbe9d80007b6d110c6f5c44b2024d4 . Seems ok to me, but the analyzer thinks different :)
Same to resizable() in unit tests
16. A part of conditional expression is always true: !count.
https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/test/blocks.cxx#L774
17. Expression 'index == - 1' is always true.
https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/src/Fl_Menu_add.cxx#L179

**Comment by MatthiasWM** [comment]
> On Dec 27, 2018, at 14:35, Pavel Shlyak <notifications@github.com> wrote:
> 
> @MatthiasWM thanks a lot for your quick response!
> I have some more points here:
> 13. Dereferencing of the null pointer 'past' might take place.
> https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/src/gl_draw.cxx#L109

The code was correct, just a bit convoluted. I rewrote and reformatted it a little.

> 14. The size of the allocated memory buffer is not a multiple of the element size. I guess it's intentional, but it still doesn't seem to be safe.
> https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/src/Fl_JPEG_Image.cxx#L259

Again, the code executed correctly, but the C style type casting wasn't necessary, so I removed that.

> 15. An object is used as an argument to its own method. Consider checking the first actual argument of the 'hotspot' function.
> https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/fluid/about_panel.cxx#L271
> This one was added by 3ef18e4 . Seems ok to me, but the analyzer thinks different :)
> Same to resizable() in unit tests

The analyzer has no clue. Sure, this is not beautiful, but this isn't Java, where everything needs to be spelled out either.

> 16. A part of conditional expression is always true: !count.
> https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/test/blocks.cxx#L774

Sigh, yes. Time waster. Made it to level 8 though.

> 17. Expression 'index == - 1' is always true.
> https://github.com/fltk/fltk/blob/75eefbcd42e7117de110f1d77e892912a24fc0a4/src/Fl_Menu_add.cxx#L179

Hmmja, ok.

**Comment by shlyakpavel** [comment]
Thanks a lot for your interest on the topic!
I'm closing this for now. I am going to return soon with a project of mine that you might find interesting :)
Have a nice day!
